/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lfrs;

import com.sun.javafx.scene.EnteredExitedHandler;
import java.awt.Color;
import java.awt.Component;
import java.awt.Label;
import java.awt.Panel;
import java.awt.TextField;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author NatalieM
 */
public class FlightViewForm extends javax.swing.JFrame implements FlightSystemViewable {

    private Controller controller;
    private ResourceBundle rb;

    /**
     * Creates new form ViewForm
     */
    public FlightViewForm() {
        this.controller = new Controller(new Flight(), null, this);
        Locale l = Locale.getDefault();
        this.rb = ResourceBundle.getBundle("lfrs/Bundle", l);
        initComponents();
        controller.updateFlightView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFlightButton = new javax.swing.JButton();
        removeFlightButton = new javax.swing.JButton();
        updateFlightButton = new javax.swing.JButton();
        cancelTicketButton = new javax.swing.JButton();
        issueTicketButton = new javax.swing.JButton();
        textFieldPanel = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        cancelTicketButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addFlightButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lfrs/Bundle"); // NOI18N
        addFlightButton.setText(bundle.getString("addAFlight")); // NOI18N
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        removeFlightButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removeFlightButton.setText(bundle.getString("removeAFlight")); // NOI18N
        removeFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFlightButtonActionPerformed(evt);
            }
        });

        updateFlightButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateFlightButton.setText(bundle.getString("updateAFlight")); // NOI18N
        updateFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightButtonActionPerformed(evt);
            }
        });

        cancelTicketButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelTicketButton.setText(bundle.getString("cancelATicket")); // NOI18N
        cancelTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketButtonActionPerformed(evt);
            }
        });

        issueTicketButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issueTicketButton.setText(bundle.getString("issueATicket")); // NOI18N
        issueTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTicketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textFieldPanelLayout = new javax.swing.GroupLayout(textFieldPanel);
        textFieldPanel.setLayout(textFieldPanelLayout);
        textFieldPanelLayout.setHorizontalGroup(
            textFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        textFieldPanelLayout.setVerticalGroup(
            textFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        cancelTicketButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelTicketButton1.setText(bundle.getString("viewReservedFlights")); // NOI18N
        cancelTicketButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelTicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issueTicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelTicketButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(textFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(addFlightButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeFlightButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateFlightButton)
                        .addGap(18, 18, 18)
                        .addComponent(issueTicketButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelTicketButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelTicketButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(textFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        textFieldPanel.removeAll();
        for (int i = 0; i < 8; i++) {
            TextField textField = new TextField();
            textField.setVisible(true);
            textField.setBounds(0, 0 + (50 * i), 200, 25);
            textFieldPanel.add(textField);
        }

        submitButton.setText(rb.getString("addAFlight"));
        submitButton.setVisible(true);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String textFieldJoined = "";
            for (Component comp : textFieldPanel.getComponents()) {
                if (comp instanceof TextField) {
                    TextField textField = (TextField) comp;
                    textFieldJoined += textField.getText() + ",";
                }
            }

            String[] splittedValues = textFieldJoined.split(",");
            Flight flightToAdd = new Flight(splittedValues[0], splittedValues[1], splittedValues[2], splittedValues[3], Integer.parseInt(splittedValues[4]), Integer.parseInt(splittedValues[5]), Integer.parseInt(splittedValues[6]), Double.parseDouble(splittedValues[7]));

            controller.addFlight(flightToAdd);
            controller.updateFlightView();

            for (Component comp : textFieldPanel.getComponents()) {
                if (comp instanceof TextField) {
                    TextField textField = (TextField) comp;
                    textField.setText("");
                }
            }
        } catch (Exception ex) {

        }
    }

    private void removeFlightActionPerformed(java.awt.event.ActionEvent evt) {
        TextField flightNo = (TextField) textFieldPanel.getComponent(0);
        String flightNumberString = flightNo.getText();
        controller.removeFlight(flightNumberString);
        controller.updateFlightView();
    }

    private void removeFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFlightButtonActionPerformed
        textFieldPanel.removeAll();
        TextField textField = new TextField();
        textField.setVisible(true);
        textField.setBounds(0, 0, 200, 25);
        textFieldPanel.add(textField);

        submitButton.setText(rb.getString("removeAFlight"));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFlightActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_removeFlightButtonActionPerformed

    private void updateFlightActionPerformed(java.awt.event.ActionEvent evt) {
        String flightNo = ((TextField) textFieldPanel.getComponent(0)).getText();
        String field = ((TextField) textFieldPanel.getComponent(1)).getText();
        String newValue = ((TextField) textFieldPanel.getComponent(2)).getText();

        if (newValue.equalsIgnoreCase("duration") || newValue.equalsIgnoreCase("seats") || newValue.equalsIgnoreCase("available")) {
            Integer.parseInt(newValue);
        } else if (newValue.equalsIgnoreCase("amount")) {
            Double.parseDouble(newValue);
        }
        controller.updateFlightData(flightNo, field, newValue);
        controller.updateFlightView();
    }

    private void updateFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightButtonActionPerformed
        textFieldPanel.removeAll();
        for (int i = 0; i < 3; i++) {
            TextField textField = new TextField();
            textField.setVisible(true);
            textField.setBounds(0, 0 + (50 * i), 200, 25);
            textFieldPanel.add(textField);
        }

        submitButton.setText(rb.getString("updateAFlight"));
        submitButton.setVisible(true);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_updateFlightButtonActionPerformed

    private void issueTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueTicketButtonActionPerformed
        textFieldPanel.removeAll();
        for (int i = 0; i < 4; i++) {
            TextField textField = new TextField();
            textField.setVisible(true);
            textField.setBounds(0, 0 + (50 * i), 200, 25);
            textFieldPanel.add(textField);
        }
        submitButton.setText(rb.getString("issueATicket"));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTicketActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_issueTicketButtonActionPerformed

    private void cancelTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketButtonActionPerformed
        textFieldPanel.removeAll();
        for (int i = 0; i < 2; i++) {
            TextField textField = new TextField();
            textField.setVisible(true);
            textField.setBounds(0, 0 + (50 * i), 200, 25);
            textFieldPanel.add(textField);
        }
        submitButton.setText(rb.getString("cancelATicket"));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_cancelTicketButtonActionPerformed

    private void cancelTicketButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketButton1ActionPerformed
        printBoard(Controller.viewBookedFlights());
    }//GEN-LAST:event_cancelTicketButton1ActionPerformed
    private void cancelTicketActionPerformed(java.awt.event.ActionEvent evt) {
        Label messageLabel = new Label();
        messageLabel.setVisible(true);
        messageLabel.setBounds(0, 250, 300, 25);
        textFieldPanel.add(messageLabel);
        try {
            int ticketNo = Integer.parseInt(((TextField) textFieldPanel.getComponent(0)).getText());
            int passNo = Integer.parseInt(((TextField) textFieldPanel.getComponent(1)).getText());
            if (controller.cancelFlight(ticketNo, passNo)) {
                messageLabel.setText(rb.getString("ticketCancelled"));
            } else {
                messageLabel.setText(rb.getString("failedTicketNotFound"));
                messageLabel.setForeground(Color.red);
            }
        } catch (Exception e) {
            messageLabel.setText(rb.getString("failedToCancelTicket") + e.getMessage());
            messageLabel.setForeground(Color.red);
            messageLabel.revalidate();
            messageLabel.repaint();
        }
    }

    private void issueTicketActionPerformed(java.awt.event.ActionEvent evt) {
        Label messageLabel = new Label();
        messageLabel.setVisible(true);
        messageLabel.setBounds(0, 250, 300, 25);
        textFieldPanel.add(messageLabel);
        try {
            Client client = new Client((Integer.parseInt(((TextField) textFieldPanel.getComponent(1)).getText())),
                    ((TextField) textFieldPanel.getComponent(2)).getText(),
                    ((TextField) textFieldPanel.getComponent(3)).getText());
            controller.addToClientTable(client);
            controller.issueTicket(((TextField) textFieldPanel.getComponent(0)).getText(), client);
            messageLabel.setText(rb.getString("ticketIssued"));
        } catch (Exception e) {
            messageLabel.setText(rb.getString("failedToAddClient") + e.getMessage());
            messageLabel.setForeground(Color.red);
            messageLabel.revalidate();
            messageLabel.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FlightViewForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FlightViewForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

    }

    public void printBoard(Map<String, String> info) {
        boardPanel.removeAll();
        int y = 0;
        for (Map.Entry<String, String> entry : info.entrySet()) {
            JLabel label = new JLabel();
            label.setBounds(0, y, 600, 25);
            label.setText(entry.getKey() + " " + entry.getValue());
            boardPanel.add(label);
            y += 25;
        }
        boardPanel.revalidate();
        boardPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightButton;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton cancelTicketButton;
    private javax.swing.JButton cancelTicketButton1;
    private javax.swing.JButton issueTicketButton;
    private javax.swing.JButton removeFlightButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel textFieldPanel;
    private javax.swing.JButton updateFlightButton;
    // End of variables declaration//GEN-END:variables

}
